/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as CartRouteImport } from './routes/cart'
import { Route as MarketRouteImport } from './routes/market'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as SecondaryRouteImport } from './routes/secondary'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CropIdRouteImport } from './routes/crop.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SecondaryRoute = SecondaryRouteImport.update({
  id: '/secondary',
  path: '/secondary',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CropIdRoute = CropIdRouteImport.update({
  id: '/crop/$id',
  path: '/crop/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk': typeof BulkRoute
  '/cart': typeof CartRoute
  '/market': typeof MarketRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/secondary': typeof SecondaryRoute
  '/settings': typeof SettingsRoute
  '/crop/$id': typeof CropIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk': typeof BulkRoute
  '/cart': typeof CartRoute
  '/market': typeof MarketRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/secondary': typeof SecondaryRoute
  '/settings': typeof SettingsRoute
  '/crop/$id': typeof CropIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk': typeof BulkRoute
  '/cart': typeof CartRoute
  '/market': typeof MarketRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/secondary': typeof SecondaryRoute
  '/settings': typeof SettingsRoute
  '/crop/$id': typeof CropIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bulk'
    | '/cart'
    | '/market'
    | '/notifications'
    | '/orders'
    | '/secondary'
    | '/settings'
    | '/crop/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bulk'
    | '/cart'
    | '/market'
    | '/notifications'
    | '/orders'
    | '/secondary'
    | '/settings'
    | '/crop/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bulk'
    | '/cart'
    | '/market'
    | '/notifications'
    | '/orders'
    | '/secondary'
    | '/settings'
    | '/crop/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BulkRoute: typeof BulkRoute
  CartRoute: typeof CartRoute
  MarketRoute: typeof MarketRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  SecondaryRoute: typeof SecondaryRoute
  SettingsRoute: typeof SettingsRoute
  CropIdRoute: typeof CropIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secondary': {
      id: '/secondary'
      path: '/secondary'
      fullPath: '/secondary'
      preLoaderRoute: typeof SecondaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop/$id': {
      id: '/crop/$id'
      path: '/crop/$id'
      fullPath: '/crop/$id'
      preLoaderRoute: typeof CropIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BulkRoute: BulkRoute,
  CartRoute: CartRoute,
  MarketRoute: MarketRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  SecondaryRoute: SecondaryRoute,
  SettingsRoute: SettingsRoute,
  CropIdRoute: CropIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
